### ISSUE TITLE
Distribution of Oboe?

### ISSUE THREAD

**Issue by dturner** [felipecsl/ktnes#4]
Would it be preferable to you to have a binary distribution of Oboe? e.g. `libOboe.so` for each target architecture? 

This would save your users from having to independently download Oboe in order to build ktnes. Or is there some other way you could introduce the Oboe dependency so that the source is downloaded automatically? 

Really just interested in making Oboe as easy for developers to use as possible so interested in your thoughts.

**Comment by felipecsl** [comment]
@dturner yes, that would be highly preferable, however I'm not sure we'd be able to still reference Oboe header files that way (eg.: `AudioStreamCallback.h`)? I'm not super familiar with JNI so I'm gonna defer to you on that.
Either way, having to manually clone Oboe in order to build projects that depend on it seems like high barrier of entry and rather unnecessary? Should we open an issue on the Oboe repo for this instead?

**Comment by dturner** [comment]
Yes please open an issue on the Oboe repo. The binary distribution would include the headers so there'd be no problem for you there.

**Comment by felipecsl** [comment]
Closing in favor of https://github.com/google/oboe/issues/230
